2024-05-04 05:04:16,293 INFO    MainThread:3947 [wandb_setup.py:_flush():69] setting env: {}
2024-05-04 05:04:16,294 INFO    MainThread:3947 [wandb_setup.py:_flush():69] setting login settings: {}
2024-05-04 05:04:16,294 INFO    MainThread:3947 [wandb_init.py:_log_setup():337] Logging user logs to /zengdaojian/litianle/Mycode/Mol-chat/LLaMA-Factory/examples/full_multi_gpu/wandb/run-20240504_050416-1c0byoeg/logs/debug.log
2024-05-04 05:04:16,294 INFO    MainThread:3947 [wandb_init.py:_log_setup():338] Logging internal logs to /zengdaojian/litianle/Mycode/Mol-chat/LLaMA-Factory/examples/full_multi_gpu/wandb/run-20240504_050416-1c0byoeg/logs/debug-internal.log
2024-05-04 05:04:16,294 INFO    MainThread:3947 [wandb_init.py:init():370] calling init triggers
2024-05-04 05:04:16,294 INFO    MainThread:3947 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2024-05-04 05:04:16,295 INFO    MainThread:3947 [wandb_init.py:init():419] starting backend
2024-05-04 05:04:16,295 INFO    MainThread:3947 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-04 05:04:16,345 INFO    MainThread:3947 [backend.py:ensure_launched():135] starting backend process...
2024-05-04 05:04:16,390 INFO    MainThread:3947 [backend.py:ensure_launched():139] started backend process with pid: 22370
2024-05-04 05:04:16,391 INFO    MainThread:3947 [wandb_init.py:init():424] backend started and connected
2024-05-04 05:04:16,393 INFO    MainThread:3947 [wandb_init.py:init():472] updated telemetry
2024-05-04 05:04:16,394 INFO    MainThread:3947 [wandb_init.py:init():491] communicating current version
2024-05-04 05:04:20,278 INFO    MainThread:3947 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.16.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-05-04 05:04:20,278 INFO    MainThread:3947 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2024-05-04 05:04:50,279 INFO    MainThread:3947 [interface.py:_communicate_run():656] couldn't get run from backend
2024-05-04 05:04:50,280 ERROR   MainThread:3947 [wandb_init.py:init():508] backend process timed out
2024-05-04 05:04:50,280 ERROR   MainThread:3947 [wandb_init.py:init():517] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
